### ISSUE TITLE
Unhandled Exception: System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by tkrokli** [jackpoz/BotFarm#13]
Using your uploaded files @ https://ci.appveyor.com/project/jackpoz/botfarm/build/artifacts, BotFarm will not get past this point in the startup process. The same happens if I compile the source in VS2013 Update 5, following the guide by compiling the CLI source first and then use the cli.dll in the C# source before compiling BotFarm.sln - looks OK for the x64 compile, no errors and no warnings.

Only thing that changes is the path to the source files in the output in the BotFarm console window:
```
Waiting for BotFactory account to login
botfarm - Authentication succeeded!
botfarm - Requesting realm list

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Client.AutomatedGame.PresentRealmList(WorldServerList realmList) in c:\projects\botfarm\Client\AutomatedGame.cs:line 204
   at Client.Authentication.Network.AuthSocket.ReadCallback(IAsyncResult result) in c:\projects\botfarm\Client\Authentication\Network\AuthSocket.cs:line 365
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

Configuration file BotFarm.exe.config : http://pastebin.com/UuPCbihJ
(absolute path to map, vmap & mmap folders, correct account info etc.)

Below is the output from a Debug compile. Not sure if the extra info is more useful than the above.
```
Waiting for BotFactory account to login
botfarm - Authentication succeeded!
botfarm - Requesting realm list

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Client.Authentication.WorldServerList.get_Item(Int32 index) in c:\Build\BotFarm_x64\Client\Authentication\WorldServerList.cs:line 25
   at Client.AutomatedGame.PresentRealmList(WorldServerList realmList) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 204
   at Client.Authentication.Network.AuthSocket.HandleRealmList() in c:\Build\BotFarm_x64\Client\Authentication\Network\AuthSocket.cs:line 319
   at Client.Authentication.Network.AuthSocket.ReadCallback(IAsyncResult result) in c:\Build\BotFarm_x64\Client\Authentication\Network\AuthSocket.cs:line 365
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by jackpoz** [comment]
```xml
<setting name="RealmID" serializeAs="String">
    <value>1</value>
</setting>
```
is this value correct ? if you have only 1 realm than you want to specify 0 there instead of 1

**Comment by tkrokli** [comment]
OK. I thought the realm ID would be 1 for the first realm, like in `auth`.`realmlist`.`id`, reading the value from the database. I will test it again with 0 instead then.

**Comment by tkrokli** [comment]
By the way, does this console output look normal, that it will look like this even if everything is correct?
```
botfarm - Server has closed the connection
botfarm - Authentication succeeded!
botfarm - Requesting realm list
botfarm - Connecting to realm Trinity
botfarm - An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdateData() in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 796
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdatePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 620
   at Client.AutomatedGame.HandleCompressedUpdateObject(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 497
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdateData() in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 796
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdatePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 620
   at Client.AutomatedGame.HandleCompressedUpdateObject(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 497
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdateData() in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 796
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdatePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 620
   at Client.AutomatedGame.HandleCompressedUpdateObject(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 497
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - The given key was not present in the dictionary.    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Client.AutomatedGame.UpdateObjectHandler.HandleMonsterMovementPacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 639
   at Client.AutomatedGame.HandleMonsterMove(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 503
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - The given key was not present in the dictionary.    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Client.AutomatedGame.UpdateObjectHandler.HandleMonsterMovementPacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 639
   at Client.AutomatedGame.HandleMonsterMove(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 503
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - Server has closed the connection
botfarm - Authentication succeeded!
botfarm - Requesting realm list
botfarm - Connecting to realm Trinity
botfarm - An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdateData() in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 796
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdatePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 620
   at Client.AutomatedGame.HandleCompressedUpdateObject(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 497
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdateData() in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 796
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdatePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 620
   at Client.AutomatedGame.HandleCompressedUpdateObject(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 497
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdateData() in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 796
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdatePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 620
   at Client.AutomatedGame.HandleCompressedUpdateObject(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 497
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - Server has closed the connection
botfarm - Authentication succeeded!
botfarm - Requesting realm list
botfarm - Connecting to realm Trinity
botfarm - An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdateData() in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 796
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdatePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 620
   at Client.AutomatedGame.HandleCompressedUpdateObject(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 497
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdateData() in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 796
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdatePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 620
   at Client.AutomatedGame.HandleCompressedUpdateObject(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 497
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
botfarm - An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdateData() in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 796
   at Client.AutomatedGame.UpdateObjectHandler.HandleUpdatePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 620
   at Client.AutomatedGame.HandleCompressedUpdateObject(InPacket packet) in c:\Build\BotFarm_x64\Client\AutomatedGame.cs:line 497
   at Client.World.Network.WorldSocket.HandlePacket(InPacket packet) in c:\Build\BotFarm_x64\Client\World\Network\WorldSocket.cs:line 386
```

**Comment by jackpoz** [comment]
> Why does it say "Unknown account name" on some of the lines?

did you read carefully https://github.com/jackpoz/BotFarm/blob/master/README.md , in particular
>fill the Username and Password fields with an account with ".account create" permissions

?

**Comment by tkrokli** [comment]
Yes, I have got 4 accounts in the DB, all of them are gmlevel 3 and with characters. If any of them had been lower in gmlevel or without characters, I could understand it. I tried using any of those accounts in the form. I also created one account with the same name and password as the default, admin/admin.

**Comment by jackpoz** [comment]
gmlevel 3 and ".account create" permissions are 2 different things. you should log ingame with the account you chose and write ".account create" and verify it actually creates an account with the username and password you'll specify

**Comment by jackpoz** [comment]
https://github.com/jackpoz/BotFarm/commit/a4648c21767cb0c6f1c124d16eabc5f60e396d31
