### ISSUE TITLE
My BotFarm.exe crashes :(

### ISSUE THREAD

**Issue by sout12** [jackpoz/BotFarm#23]
My Botfarm.exe crashes when i start it up. Here is link: What it says when it crashes then it doesn't respond
![sadsa](https://cloud.githubusercontent.com/assets/15899910/11230034/286e680a-8d69-11e5-9664-5d7a1c0d85af.png) That is what it says when it crashes :(

**Comment by tkrokli** [comment]
@sout12 : make **BotFarm.exe** use Windows Administrator permissions via the Compatibility tab.
I got a similar error message before I did that, because I use the C:\Program Files\TrinityCore\ folder:
```
Unhandled Exception: System.InvalidOperationException: There was an error generating the XML document. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterList1.Write3_ArrayOfBotInfo(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(TextWriter textWriter, Object o, XmlSerializerNamespaces namespaces)
   at BotFarm.BotFactory.SaveBotInfos() in C:\projects\botfarm\BotFarm\BotFactory.cs:line 262
   at BotFarm.BotFactory.SetupFactory(Int32 botCount) in C:\projects\botfarm\BotFarm\BotFactory.cs:line 218
   at BotFarm.Program.Main(String[] args) in C:\projects\botfarm\BotFarm\Program.cs:line 19
```

![botfarm properties](https://cloud.githubusercontent.com/assets/4903600/11231335/b339f3f8-8da7-11e5-9df0-680b01c1f43c.png)
After setting BotFarm.exe to run as Administrator, the error disappeared.

**Comment by tkrokli** [comment]
If your issue was solved by using the suggested solution, please close this issue. :turtle:

**Comment by jackpoz** [comment]
Probably better to handle the exception if this issue happens to users

**Comment by jackpoz** [comment]
Lol, don't close issues I reopened, I want to handle this exception.

**Comment by jackpoz** [comment]
https://github.com/jackpoz/BotFarm/commit/a5dab30041130c31c1077aaefa5ca29466c3ea33
next time it's going to write a more understandable message
